### ISSUE TITLE
Connection refused after large number of queries

### ISSUE THREAD

**Issue by purvanshi** [stanfordnlp/stanza#16]
When I launched the server for using the Python client for the CoreNLP server this exception occurs-

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7faca3ddb358>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7faca3ddb358>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spa.py", line 2, in <module>
    client = CoreNLPClient(server='http://localhost:9000', default_annotators=['ssplit', 'tokenize', 'lemma', 'pos', 'ner'])
  File "/home/puru/Documents/d/arithmetic/code/stanza/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7faca3ddb358>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by wadkar** [comment]
I am afraid there is little that can be diagnosed from your error log. Simply put, the issue is what the error says - _Connection to the (CoreNLP) server was refused_.

Are you sure your CoreNLP server is running, and accepting connections on the `localhost:9000`?

**Comment by vzhong** [comment]
Hi @purvanshi , can you verify that the server is running like @wadkar suggested? Instructions on how to run the server can be found here: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

**Comment by vzhong** [comment]
Closing due to lack of response.

**Comment by bkgoksel** [comment]
Having the same issue, across different machines. My client works fine for the first ~10k annotation text snippets I send, but then crashes with this error after an arbitrary number of requests. Running the server while inspecting the logs, it simply stops printing more logs.
Interestingly, if I rerun the client script after the first run crashes, it again works fine for ~10k requests and then crashes, all the while the server is running.

**Comment by vzhong** [comment]
@gangeli @arunchaganty any thoughts? I have actually encountered this as well... I think this might be something with the java server.

**Comment by vzhong** [comment]
@bkgoksel can you please help me try out a fix, since I'm having some trouble reproducing this failure?

Can you install `stanza` in dev mode and try adding `r.connection.close()` to line `101` of your `stanza/nlp/corenlp.py` and see if that fixes the problem?

**Comment by bkgoksel** [comment]
Looking at it in a moment, will edit this reply once done.

**Comment by bkgoksel** [comment]
@vzhong Thanks for your help! I was actually using the _request method call directly because I needed to pass different properties for the annotator, so I found the corresponding place to add r.connection.close() in my codebsae:
`from stanza.nlp.corenlp import CoreNLPClient
from stanza.nlp.corenlp import CoreNLP_pb2
from stanza.nlp.corenlp import AnnotatedDocument
from google.protobuf.internal.decoder import _DecodeVarint

class Annotator:
    def __init__(self, annotators=['ssplit', 'pos'], server="http://localhost:9000"):
        self.client = CoreNLPClient(server=server, default_annotators=annotators)

    def annotate_pos(self, text):
        properties = {
            'annotators': ','.join(self.client.default_annotators),
            'outputFormat': 'serialized',
            'tokenize.whitespace': 'true',
            'serializer': 'edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer'
        }
        r = self.client._request(text, properties)
        buffer = r.content  # bytes
        size, pos = _DecodeVarint(buffer, 0)
        buffer = buffer[pos:(pos + size)]
        **r.connection.close()**
        doc = CoreNLP_pb2.Document()
        doc.ParseFromString(buffer)
        annotations = AnnotatedDocument.from_pb(doc)
        tokens = []
        for sentence in annotations.sentences:
            tokens += [token.pos for token in sentence.tokens]
        return tokens`

However the issue persists. I'll try to use the regular annotate method with the modification you suggested and will let you know.

**Comment by vzhong** [comment]
Yes I think what is happening is that we are running out of ports for `requests` to communicate with the CoreNLP server.

Not sure what the correct fix is, so I will reopen this issue until a fix is found.

Meanwhile, a hack that I have used is to wrap the request call with a `try` and `except` and retry the query after `sleep`ing for a couple seconds.

**Comment by jhowliu** [comment]
Hi @bkgoksel ,

I passed the custom properties ('tokenize.whitespace': 'true') for the annotators as you mentioned above. But I still got the wrong result not cut by whitespace. Do you have any suggestions?

Thanks.

**Comment by ghost** [comment]
Getting the same issue here. The server does not seem to be able to digest a heavy load of requests :/

**Comment by gangeli** [comment]
What counts as a heavy load? Are we talking about 100 concurrent requests, or 100,000?

**Comment by ghost** [comment]
@gangeli Idk.. I parallelize the work - so having 8 processes sending requests to the server appears to be too much. 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc56c06fe10>: Failed to establish a new connection: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc56c06fe10>: Failed to establish a new connection: [Errno 99] Cannot assign requested address',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pycorenlp/corenlp.py", line 19, in annotate
    requests.get(self.server_url)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc56c06fe10>: Failed to establish a new connection: [Errno 99] Cannot assign requested address',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "<ipython-input-41-25498d9e314a>", line 33, in _nlp_annotate
    return [json.loads(self.nlp.annotate(document, properties=self.properties)) for document in documents_part]
  File "<ipython-input-41-25498d9e314a>", line 33, in <listcomp>
    return [json.loads(self.nlp.annotate(document, properties=self.properties)) for document in documents_part]
  File "/usr/local/lib/python3.5/dist-packages/pycorenlp/corenlp.py", line 21, in annotate
    raise Exception('Check whether you have started the CoreNLP server e.g.\n'
Exception: Check whether you have started the CoreNLP server e.g.
$ cd stanford-corenlp-full-2015-12-09/ 
$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-42-b824e1fa3bb8> in <module>()
----> 1 CoreNLPSentenceSplitter().set_url('http://localhost:9000').fit_transform(train.comment_text)

<ipython-input-41-25498d9e314a> in fit_transform(self, X, y)
     70 
     71     def fit_transform(self, X, y=None):
---> 72         return self.fit(X, y).transform(X)

<ipython-input-41-25498d9e314a> in transform(self, documents)
     52     def transform(self, documents):
     53 
---> 54         annoated_documents = self.nlp.transform(documents)
     55 
     56         docs = list()

<ipython-input-41-25498d9e314a> in transform(self, documents)
     24 
     25     def transform(self, documents):
---> 26         return parallelize(documents, self._nlp_annotate, nb_partitions=8, nb_cores=8)
     27         #return self._nlp_annotate(documents)
     28 

<ipython-input-41-25498d9e314a> in parallelize(splittable, func, nb_partitions, nb_cores)
      2     df_split = np.array_split(splittable, nb_partitions)
      3     pool = Pool(nb_cores)
----> 4     df = np.concatenate(pool.map(func, df_split))
      5     pool.close()
      6     pool.join()

/usr/lib/python3.5/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

Exception: Check whether you have started the CoreNLP server e.g.
$ cd stanford-corenlp-full-2015-12-09/ 
$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
```

**Comment by gangeli** [comment]
Is the server giving off any errors during this?

**Comment by ghost** [comment]
@gangeli That's the thing, I'm not getting anything from the server. It just stops writing to stdout.
  
This is how I am requesting the server. I use a `multiprocessing.Pool` to do so. 

```python
def parallelize(splittable, func, nb_partitions=cpu_count(), nb_cores=cpu_count()):
    df_split = np.array_split(splittable, nb_partitions)
    pool = Pool(nb_cores)
    df = np.concatenate(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df

class CoreNLPExtractor(BaseEstimator):

    def __init__(self, properties):
        self.properties = properties
        self.nlp = None

    def set_server_url(self, server_url):
        """
        The server url should not be accounted as a model parameter thus it is not set in the constructor.
        """
        self.nlp = StanfordCoreNLP(server_url=server_url)
        return self

    def fit(self, documents, y=None):
        return self

    def transform(self, documents):
        return parallelize(documents, self._nlp_annotate, nb_partitions=8, nb_cores=8)
        #return self._nlp_annotate(documents)
        
    def fit_transform(self, documents, y=None):
        return self.fit(documents, y).transform(documents)

    def _nlp_annotate(self, documents_part):
        return [json.loads(self.nlp.annotate(document, properties=self.properties)) for document in documents_part]
```

**Comment by vzhong** [comment]
Typically `OSError: [Errno 99] Cannot assign requested address` means that you have used all the ports allocated by the OS (see this [stackoverflow post](https://stackoverflow.com/questions/11190595/repeated-post-request-is-causing-error-socket-error-99-cannot-assign-reques?rq=1)). I thought we fixed this in #18 , and I don't see why the fix should not work even for your multi-processing case (but I don't see the error message introduced by the fix about waiting for available ports in your log). Can you please verify that you are using the latest stanza? e.g. install it from Github. Also I am not sure whether multiprocessing helps in this case. You only have one instance of the CoreNLP server, right? You are sending it data from multiple processes, but the bottleneck of a single server remains. What is limiting the throughput is the server itself, as well as the total number of ports allocated by the OS.

**Comment by ghost** [comment]
@vzhong I am using the latest version from https://stanfordnlp.github.io/CoreNLP/download.html and I run the server as

```
java -mx48g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
```

Does that version of the server include the fix already?

I can't try the latest version from the github right now but I can do on Sunday.

**Comment by vzhong** [comment]
The fix is not the the server but for the Stanza client. You need to make
sure your Python client is the latest. You can reinstall it from github.

**Comment by ghost** [comment]
@vzhong Sorry, that's my bad. I am not using stanza - I thought I am posting for the CoreNLP Server. I use [`pycorenlp`](https://github.com/smilli/py-corenlp) as client.

**Comment by vzhong** [comment]
This is the support page for only stanza..

**Comment by ndvbd** [comment]
Same problem here. Is there a solution to this problem?

**Comment by J38** [comment]
This is an older Python project, and I think I will shut it down soon.  You should switch to this library:

https://github.com/stanfordnlp/stanfordnlp

**Comment by narukamiko** [comment]
Same issue. Is there any solution?
