### ISSUE TITLE
Release plans and beta testing

### ISSUE THREAD

**Issue by wadkar** [stanfordnlp/stanza#17]
Hi,

I am using `stanza` regularly for development. My primary use case is for the `stanza.nlp.corenlp.CoreNLPClient()` but I also reuse many classes from `stanza.nlp.data` module and the `stanza.text` module.

I would be more than happy to help with:
- Testing (especially the low hanging fruits like python2/3 compatibility)
- Documentation (.rst formatting, sphinx-doc-building, adding API usage examples) 
- Packaging, release management

I didn't see a `CONTRIBUTING.md` so thought to create an issue. Thoughts?

**Comment by J38** [comment]
We're working on Stanford CoreNLP 3.8.0 right now and want to release that by the end of May.  I would like to release Stanza 3.8.0 (I want to have the version numbers match) at the same time.  Probably the main use case is to make sure the Python client to the server works properly.  Thank you for the offer of assistance.  I will update this thread as we work on the release more.

**Comment by wadkar** [comment]
sounds good! Closing this issue.
