### ISSUE TITLE
Feature: GPU auto-select

### ISSUE THREAD

**Issue by hans** [stanfordnlp/stanza#4]
[Sam's question](http://nlp.stanford.edu/local/qa/76/there-easy-programmatic-find-which-gpu-are-free-jag-machine) re: automatically finding the most free GPU on a machine sounds to me like a good Stanza feature. 

> I'm hoping to create a job that I can launch through PBS on the jag queue that will automatically use the least-busy GPU on the machine that it's assigned to.

What do you think? I've suggested a solution on the QA post linked above:

> You could accomplish this with NVIDIA's [NVML library](https://developer.nvidia.com/nvidia-management-library-nvml) (or [`nvidia-ml-py` for Python bindings](https://pypi.python.org/pypi/nvidia-ml-py/)). Use the library to programmatically check for an open device.

If no one else is excited about this, I might add it whenever I have the requisite time + boredom.

**Comment by futurulus** [comment]
My improved version of @hans and @sleepinyourhat 's GPU script, which was languishing in research/ for a while, is moved into `stanza.cluster` as of 33d78c7084f90d8394e2c5700f95797de2116505. Bug reports and improvements welcome!
